# Generated by Django 3.2.21 on 2023-09-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessages',
            name='foreign_key',
        ),
        migrations.AddField(
            model_name='usermessages',
            name='reciever',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='users.user'),
            preserve_default=False,
        ),
    ]
