# Generated by Django 3.2.21 on 2023-11-07 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_history_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_messages',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='history_messages',
            name='message_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.usermessages'),
        ),
    ]
