# Generated by Django 3.2.21 on 2023-11-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20231107_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History_Messages',
        ),
    ]
